
services:
  web:
    build: .
    container_name: django_app
    command:
        sh -c "python manage.py runserver 0.0.0.0:8000 y"
    ports:
      - "12500:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env