# Generated by Django 5.2.5 on 2025-08-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('acoustic', 'Acoustic'), ('decorative', 'Decorative'), ('metal', 'Metal'), ('tiles', 'Tiles'), ('mineral', 'Mineral Fiber')], max_length=20)),
                ('weight_per_sqm', models.DecimalField(decimal_places=2, help_text='Weight in KGS/m²', max_digits=5)),
                ('image_url', models.URLField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
