# Generated by Django 5.2.5 on 2025-08-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контактный запрос', 'verbose_name_plural': 'Контактные запросы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'verbose_name': 'Перевод продукта', 'verbose_name_plural': 'Переводы продуктов'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_per_sqm',
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги (через запятую)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('Ky', 'Кыргызча')], default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
