# Generated by Django 5.2.5 on 2025-08-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactinquiry_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=10, verbose_name='Язык'),
        ),
    ]
