# Generated by Django 5.2.5 on 2025-08-18 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_producttranslation_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Вид модели',
                'verbose_name_plural': 'Виды моделей',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.producttype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=10)),
                ('name', models.CharField(default='Без названия', max_length=100, verbose_name='Название')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.producttype')),
            ],
        ),
    ]
