# Generated by Django 5.2.5 on 2025-08-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_producttype_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Модель вид', 'verbose_name_plural': 'Модель виды'},
        ),
        migrations.AddField(
            model_name='producttype',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.producttype', null=True),
        ),
        migrations.AlterField(
            model_name='producttypetranslation',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.producttype'),
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='main.product')),
            ],
            options={
                'verbose_name': 'Характеристика модели',
                'verbose_name_plural': 'Характеристики моделей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=10)),
                ('name', models.CharField(max_length=200, verbose_name='Название характеристики')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Значение характеристики')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.productcharacteristic')),
            ],
            options={
                'verbose_name': 'Перевод характеристики',
                'verbose_name_plural': 'Переводы характеристик',
                'unique_together': {('characteristic', 'language')},
            },
        ),
    ]
