# Generated by Django 5.2.5 on 2025-08-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_options_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='image_url',
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.CreateModel(
            name='ProductCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=10)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.productcategory')),
            ],
            options={
                'verbose_name': 'Перевод категории',
                'verbose_name_plural': 'Переводы категорий',
                'unique_together': {('product_category', 'language')},
            },
        ),
    ]
