# Generated by Django 5.2.5 on 2025-08-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productcategory_remove_producttype_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
