# Generated by Django 5.2.5 on 2025-08-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_producttype_category_alter_productcategory_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
    ]
