# Generated by Django 5.2.5 on 2025-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='productcategorytranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
